FROM alpine:latest

WORKDIR /data

COPY schema.sql /data/

RUN apk update && \
    apk upgrade && \
    apk add --no-cache sqlite

CMD sh -c "if [ ! -f minitwit.db ]; then sqlite3 minitwit.db < schema.sql; fi"
