version: '3.4'

services:
  minitwit:
    build:
      context: .
      dockerfile: ./Dockerfile.minitwit
    ports:
      - 5000:5000
    volumes:
      - minitwit:/data

volumes:
  minitwit:
    external: false
