version: '3.4'

services:
  dbserver:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.db
    ports:
      - "27017:27017"
    networks:
      - minitwit

  webserver:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.web
    ports:
      - "5000:5000"
    networks:
        - minitwit

networks:
  minitwit:
    external: false
