version: '3.4'

services:
  init-db:
    build:
      context: .
      dockerfile: ./Dockerfile.init-db
    volumes:
      - minitwit:/data

  minitwit:
    build:
      context: .
      dockerfile: ./Dockerfile.minitwit
    ports:
      - 5000:5000
    volumes:
      - minitwit:/data
    depends_on:
      - init-db

volumes:
  minitwit:
    external: false
